"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#j7_%$l(5pi*4j8ky=!1u68dys6yo((kdkzfold4r+v01f=y@c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["social-app-prod.us-east-1.elasticbeanstalk.com", "localhost"]
CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

AWS_ACCESS_KEY_ID = 'ASIA6ODVARC3SRKWMMGO'
AWS_SECRET_ACCESS_KEY = 'qR8fPYiOU/SD4X2/rCqhGERIdAW1EivqyG9LcVHY'
AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjEFYaCXVzLXdlc3QtMiJHMEUCIBD0mA7NPy+S2gOcvhMx4hYRjw1JTl4EmTdzkITDMdT7AiEAozqAa2OmtFgiQrlY5X8EhOjrK6IWtHLVDMi+KuOQ+jgqvQII7v//////////ARAAGgw5OTIzODI4NDcxNTkiDN2cEzSWqLN/1ob14iqRArop2125xaNUVVH5BI8vM3vIHyNoFTS2ZsOfkRXBNo2kI890I2FsTztrvUmrXw/cyS0vrnYNqZ7zK/Zb/YonAQzHfaGa0HU7KEum42CJwQSn2EILhrEHRehwMKPJAmrBerMQ8g6mNRgZxyREvKqsxpy4APEhx//ODyVwADs8Zw9kkzPsiwCca22LK42yAl9q1fKE7FdOz4/6/LVKRFHJylZea7n9fe9kaVvbU+47xj/2s133g0ibxxgiGG7XnuGZcNei60uS8jNB3WulG6lyFToxWY5Ap+ZNgqRIEVN3/IT7vqnO3OrB5iFCjp2girVsGPj+2cyf+zlta11VLVXLJsGCx0gVb+c16Vc4aCq9ewP/QDDPz4y6BjqdASIgVga1vMDnbqDVZjiEMUzqdqYrnuJQSj/zFnp9jxhXkC8auEAxw+DXXcifIke+t2xZ/Cml6VONi+65wCKRp/7wZh7Qz4FxxRTRa2jTOqHAfBVc4jlDSmvf1H4nc5a+O7qXfRdO6MKPNGyqt/qG3jJjFgHv5h3hDkcRzIK9+FcTjQ9Cu7ElcyNaVyidmwtZeDCTGnM02nNJBB+fLBk='
AWS_S3_BUCKET_NAME = 'social-media-store'
AWS_REGION = 'us-east-1'
SEND_EMAIL_URL = "https://vv8apl3j3e.execute-api.us-east-1.amazonaws.com/prod/send-email"
DYNAMODB_USER_TABLE_NAME = 'Users'
DYNAMODB_POST_TABLE_NAME = 'Posts'
DYNAMODB_LIKE_TABLE_NAME = 'Likes'
DYNAMODB_COMMENT_TABLE_NAME = 'Comments'

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
