"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#j7_%$l(5pi*4j8ky=!1u68dys6yo((kdkzfold4r+v01f=y@c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["social-app-prod.us-east-1.elasticbeanstalk.com"]
CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

AWS_ACCESS_KEY_ID = 'ASIA6ODVARC3VFKC5UYQ'
AWS_SECRET_ACCESS_KEY = 'N+FZMeBo3b5e1rebHZ2R7b++jbi/9dxzCqT6RcbD'
AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjEN///////////wEaCXVzLXdlc3QtMiJHMEUCIBJcBYAiOltMvt9N35cx2iJwkz3R4ePYTTr8NvMBpvasAiEA1Q6jiZn4VvbsM4S/bcy8uFbeQzvfdQzo+5OEt4sa4pUqtAIIeBAAGgw5OTIzODI4NDcxNTkiDEUhkeitDuMwFn/yIyqRAi4uokrGV3TB6+qvL2bICoW9gNjt0QQjqV+h6GMV7bgasTSXsJgY3IBhA5m6yh4GhETYCDs7SxO8hrvcKJUdg1W+K/m143qzb14ZrVGcSaEYsl67kgChawInDABj3PCj8/Ogaweo1FIzDE6H3LWAK4/s/RCTsl7nCiRC9qYsPvaz4pPHYSlWOuZ3xkMqMyxvI8v/BGQfO6MzvP5hODfXqlfsnHV1+yvlu1X5f6jWjQ4DoNi2mbLtfLT7WTGg67vpYiLczVf2B2iguNgbPIvNNyg2FajtawEQxKraHVTTyxwEqS/Y3eoVRvyzoZjsjv78oZSZTIU1303+vGD8elTEJfk6Lu7/J7agl+o2BXubBkgFFjD81PK5BjqdAUA4A7GIp63+R+z6wMXnHU+hRXHscqHMaTvYYS3tT9vP+y59hMOLacmqQw5ZCMfYe80Csjb6nxQtR4+yuqQeutgjkAMgGDDjhJZy4bvKBXjaFMtMmlz8uwrKJTn+Ies0gEMQ2ih/xAM8ikavnZlbIqzz3f+QXemI5Nc3xqp0CSPeANf+3vR4GZ9stEzdR0+fPxTTVz3dfjwKBDo/Oe8='
AWS_S3_BUCKET_NAME = 'social-media-store'
AWS_REGION = 'us-east-1'
DYNAMODB_USER_TABLE_NAME = 'Users'
DYNAMODB_POST_TABLE_NAME = 'Posts'
DYNAMODB_LIKE_TABLE_NAME = 'Likes'
DYNAMODB_COMMENT_TABLE_NAME = 'Comments'

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
