"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#j7_%$l(5pi*4j8ky=!1u68dys6yo((kdkzfold4r+v01f=y@c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["social-app-prod.us-east-1.elasticbeanstalk.com", "localhost"]
CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

AWS_ACCESS_KEY_ID = 'ASIA6ODVARC3TQ7RXQYD'
AWS_SECRET_ACCESS_KEY = 'nCTjpb7Ef6hU5mZVItTzY/GgaG8i7if8JEUMXrSj'
AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjED0aCXVzLXdlc3QtMiJHMEUCIQCbX3w98tPNnQufP6EOPt92hgs15Y+JmENheN5NYoaUjwIgUmnQsK4GptQgQzZ9SZNI8KNXJ4CsFGzjf2VnDEtDcOMqvQII1v//////////ARAAGgw5OTIzODI4NDcxNTkiDMGRDjQ1Nn/+ynnxqSqRAlXO7lJ438fr4CqxYiKNpnScbyciQTtHB2kxnRrV4MZw45++KLrgoXc/uPYR22f2aoHPJVoPfgvt/nWPd/89wyH/i2ERiqW7CVGJZbcROMhyY6/hCNHty4WR1BktX8tZUQ2SwCPhISdL2lTMf/po2E/Quyz4bBSStKjdMisFCklF7VOqo3LYT3UuHXIuq6jzCFsG3aBgQgjUSKmXzC+fcWEofc/mH5lTb3kZg6Xwtxj8TCjka/Fq3yIKbZG9ELvggDtx7weBqARcrWYIwth68lP4QhTgsh5QhKm75uko620L/P+6IsuC383uiNN6Y2lwb3mdm6leRcQP1SFNgEdyon+9AzX8oKJhOOL+mDL3xzswjzDwm4e6BjqdAZsI9FOVpA4bYY4G+wvbmq+kWjcIw7Dpy15ji23iPMsPcfUXGzuzVfQWLJhP1bz5bfwKsst469fnOn1JfrzMCVRBrdB0ABSa4YhOLDEsYueyxzB3fln4DplTDU9vN/PyMB78HiUy6gmICxRwtS8NMtTCYX92ZjkteiRh4TeQS+WfcfkhQGa3jQjpOkwRJPViFIW4D2Aw4YMsJ7FQ/lo='
AWS_S3_BUCKET_NAME = 'social-media-store'
AWS_REGION = 'us-east-1'
SEND_EMAIL_URL = "https://vv8apl3j3e.execute-api.us-east-1.amazonaws.com/prod/send-email"
DYNAMODB_USER_TABLE_NAME = 'Users'
DYNAMODB_POST_TABLE_NAME = 'Posts'
DYNAMODB_LIKE_TABLE_NAME = 'Likes'
DYNAMODB_COMMENT_TABLE_NAME = 'Comments'

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
